version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/carbackend_new
hooks:
# ApplicationStop:
# DownloadBundle:
#  BeforeInstall test:
#    - location: scripts/before_install.sh
#      timeout: 300
#      runas: root
# Install:
  AfterInstall:
    - location: scripts/after_install.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: scripts/application_start.sh
      timeout: 300
      runas: root
# ValidateService:
